[package]
name = "fluxdb"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38", features = ["full"] }
bytes = "1.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
crossbeam-skiplist = "0.1"
crossbeam-channel = "0.5"
parking_lot = "0.12"
crc32fast = "1.4"
uuid = { version = "1.8", features = ["v4", "v5", "fast-rng", "serde"] }
clap = { version = "4.5", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
thiserror = "1.0"
byteorder = "1.5"
tempfile = "3.10"
rand = "0.8"
lz4_flex = "0.11"
zstd = "0.13"
toml = "0.8"

[[bin]]
name = "fluxdb-server"
path = "src/main.rs"

[[bin]]
name = "fluxdb-cli"
path = "src/bin/cli.rs"

[[bin]]
name = "fluxdb-bench"
path = "src/bin/bench.rs"

[[bin]]
name = "fluxdb-dump"
path = "src/bin/dump.rs"

[[bin]]
name = "fluxdb-load"
path = "src/bin/load.rs"

[[bin]]
name = "fluxdb-check"
path = "src/bin/check.rs"
