version: '3.8'

services:
  fluxdb:
    build: .
    container_name: fluxdb-server
    ports:
      - "7379:7379"   # Binary RESP / Redis-compatible Protocol
      - "7380:7380"   # HTTP REST API & Web Dashboard & /metrics
    volumes:
      - ./data:/app/data
      - ./fluxdb.toml:/app/fluxdb.toml
    restart: unless-stopped

